spring:
  application:
    name: springAuthWithKeyClockIntegration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.keycloak.serverUrl}/realms/${app.keycloak.realm}
server:
  port: 6700
  servlet:
    context-path: /auth
app:
  keycloak:
    admin:
      clientId: admin-cli
      clientSecret: 3Y0rgdaOSfQiCtVxlskUB0az0VCIDuH3
    realm: spring
    serverUrl: http://localhost:9082














